export { default as HeartIcon } from './heart.svg';
export { default as ClockSquareIcon } from './clock_square.svg';
export { default as ShieldDoneIcon } from './shield_done.svg';
export { default as PaperNoteV2Icon } from './paper_note_V2.svg';
export { default as PaperNoteV1Icon } from './paper_note_V1.svg';
export { default as LogoutIcon } from './logout.svg';
export { default as QrCodeIcon } from './qr_code.svg';
export { default as ProfileIcon } from './profileMyAccount.svg';
export { default as PhoneIcon } from './phone.svg';